/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.opentsdb.tsd;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueryStr implements org.apache.thrift.TBase<QueryStr, QueryStr._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryStr");

  private static final org.apache.thrift.protocol.TField STARTTIME_FIELD_DESC = new org.apache.thrift.protocol.TField("starttime", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ENDTIME_FIELD_DESC = new org.apache.thrift.protocol.TField("endtime", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("items", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField NOCACHE_FIELD_DESC = new org.apache.thrift.protocol.TField("nocache", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryStrStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryStrTupleSchemeFactory());
  }

  public long starttime; // required
  public long endtime; // required
  public List<Item> items; // required
  public boolean nocache; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STARTTIME((short)1, "starttime"),
    ENDTIME((short)2, "endtime"),
    ITEMS((short)3, "items"),
    NOCACHE((short)4, "nocache");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STARTTIME
          return STARTTIME;
        case 2: // ENDTIME
          return ENDTIME;
        case 3: // ITEMS
          return ITEMS;
        case 4: // NOCACHE
          return NOCACHE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STARTTIME_ISSET_ID = 0;
  private static final int __ENDTIME_ISSET_ID = 1;
  private static final int __NOCACHE_ISSET_ID = 2;
  private BitSet __isset_bit_vector = new BitSet(3);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STARTTIME, new org.apache.thrift.meta_data.FieldMetaData("starttime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ENDTIME, new org.apache.thrift.meta_data.FieldMetaData("endtime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ITEMS, new org.apache.thrift.meta_data.FieldMetaData("items", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Item.class))));
    tmpMap.put(_Fields.NOCACHE, new org.apache.thrift.meta_data.FieldMetaData("nocache", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryStr.class, metaDataMap);
  }

  public QueryStr() {
  }

  public QueryStr(
    long starttime,
    long endtime,
    List<Item> items,
    boolean nocache)
  {
    this();
    this.starttime = starttime;
    setStarttimeIsSet(true);
    this.endtime = endtime;
    setEndtimeIsSet(true);
    this.items = items;
    this.nocache = nocache;
    setNocacheIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryStr(QueryStr other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.starttime = other.starttime;
    this.endtime = other.endtime;
    if (other.isSetItems()) {
      List<Item> __this__items = new ArrayList<Item>();
      for (Item other_element : other.items) {
        __this__items.add(new Item(other_element));
      }
      this.items = __this__items;
    }
    this.nocache = other.nocache;
  }

  public QueryStr deepCopy() {
    return new QueryStr(this);
  }

  @Override
  public void clear() {
    setStarttimeIsSet(false);
    this.starttime = 0;
    setEndtimeIsSet(false);
    this.endtime = 0;
    this.items = null;
    setNocacheIsSet(false);
    this.nocache = false;
  }

  public long getStarttime() {
    return this.starttime;
  }

  public QueryStr setStarttime(long starttime) {
    this.starttime = starttime;
    setStarttimeIsSet(true);
    return this;
  }

  public void unsetStarttime() {
    __isset_bit_vector.clear(__STARTTIME_ISSET_ID);
  }

  /** Returns true if field starttime is set (has been assigned a value) and false otherwise */
  public boolean isSetStarttime() {
    return __isset_bit_vector.get(__STARTTIME_ISSET_ID);
  }

  public void setStarttimeIsSet(boolean value) {
    __isset_bit_vector.set(__STARTTIME_ISSET_ID, value);
  }

  public long getEndtime() {
    return this.endtime;
  }

  public QueryStr setEndtime(long endtime) {
    this.endtime = endtime;
    setEndtimeIsSet(true);
    return this;
  }

  public void unsetEndtime() {
    __isset_bit_vector.clear(__ENDTIME_ISSET_ID);
  }

  /** Returns true if field endtime is set (has been assigned a value) and false otherwise */
  public boolean isSetEndtime() {
    return __isset_bit_vector.get(__ENDTIME_ISSET_ID);
  }

  public void setEndtimeIsSet(boolean value) {
    __isset_bit_vector.set(__ENDTIME_ISSET_ID, value);
  }

  public int getItemsSize() {
    return (this.items == null) ? 0 : this.items.size();
  }

  public java.util.Iterator<Item> getItemsIterator() {
    return (this.items == null) ? null : this.items.iterator();
  }

  public void addToItems(Item elem) {
    if (this.items == null) {
      this.items = new ArrayList<Item>();
    }
    this.items.add(elem);
  }

  public List<Item> getItems() {
    return this.items;
  }

  public QueryStr setItems(List<Item> items) {
    this.items = items;
    return this;
  }

  public void unsetItems() {
    this.items = null;
  }

  /** Returns true if field items is set (has been assigned a value) and false otherwise */
  public boolean isSetItems() {
    return this.items != null;
  }

  public void setItemsIsSet(boolean value) {
    if (!value) {
      this.items = null;
    }
  }

  public boolean isNocache() {
    return this.nocache;
  }

  public QueryStr setNocache(boolean nocache) {
    this.nocache = nocache;
    setNocacheIsSet(true);
    return this;
  }

  public void unsetNocache() {
    __isset_bit_vector.clear(__NOCACHE_ISSET_ID);
  }

  /** Returns true if field nocache is set (has been assigned a value) and false otherwise */
  public boolean isSetNocache() {
    return __isset_bit_vector.get(__NOCACHE_ISSET_ID);
  }

  public void setNocacheIsSet(boolean value) {
    __isset_bit_vector.set(__NOCACHE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STARTTIME:
      if (value == null) {
        unsetStarttime();
      } else {
        setStarttime((Long)value);
      }
      break;

    case ENDTIME:
      if (value == null) {
        unsetEndtime();
      } else {
        setEndtime((Long)value);
      }
      break;

    case ITEMS:
      if (value == null) {
        unsetItems();
      } else {
        setItems((List<Item>)value);
      }
      break;

    case NOCACHE:
      if (value == null) {
        unsetNocache();
      } else {
        setNocache((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STARTTIME:
      return Long.valueOf(getStarttime());

    case ENDTIME:
      return Long.valueOf(getEndtime());

    case ITEMS:
      return getItems();

    case NOCACHE:
      return Boolean.valueOf(isNocache());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STARTTIME:
      return isSetStarttime();
    case ENDTIME:
      return isSetEndtime();
    case ITEMS:
      return isSetItems();
    case NOCACHE:
      return isSetNocache();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryStr)
      return this.equals((QueryStr)that);
    return false;
  }

  public boolean equals(QueryStr that) {
    if (that == null)
      return false;

    boolean this_present_starttime = true;
    boolean that_present_starttime = true;
    if (this_present_starttime || that_present_starttime) {
      if (!(this_present_starttime && that_present_starttime))
        return false;
      if (this.starttime != that.starttime)
        return false;
    }

    boolean this_present_endtime = true;
    boolean that_present_endtime = true;
    if (this_present_endtime || that_present_endtime) {
      if (!(this_present_endtime && that_present_endtime))
        return false;
      if (this.endtime != that.endtime)
        return false;
    }

    boolean this_present_items = true && this.isSetItems();
    boolean that_present_items = true && that.isSetItems();
    if (this_present_items || that_present_items) {
      if (!(this_present_items && that_present_items))
        return false;
      if (!this.items.equals(that.items))
        return false;
    }

    boolean this_present_nocache = true;
    boolean that_present_nocache = true;
    if (this_present_nocache || that_present_nocache) {
      if (!(this_present_nocache && that_present_nocache))
        return false;
      if (this.nocache != that.nocache)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(QueryStr other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    QueryStr typedOther = (QueryStr)other;

    lastComparison = Boolean.valueOf(isSetStarttime()).compareTo(typedOther.isSetStarttime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStarttime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.starttime, typedOther.starttime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEndtime()).compareTo(typedOther.isSetEndtime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndtime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endtime, typedOther.endtime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetItems()).compareTo(typedOther.isSetItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.items, typedOther.items);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNocache()).compareTo(typedOther.isSetNocache());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNocache()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nocache, typedOther.nocache);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryStr(");
    boolean first = true;

    sb.append("starttime:");
    sb.append(this.starttime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("endtime:");
    sb.append(this.endtime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("items:");
    if (this.items == null) {
      sb.append("null");
    } else {
      sb.append(this.items);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nocache:");
    sb.append(this.nocache);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryStrStandardSchemeFactory implements SchemeFactory {
    public QueryStrStandardScheme getScheme() {
      return new QueryStrStandardScheme();
    }
  }

  private static class QueryStrStandardScheme extends StandardScheme<QueryStr> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryStr struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STARTTIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.starttime = iprot.readI64();
              struct.setStarttimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ENDTIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endtime = iprot.readI64();
              struct.setEndtimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ITEMS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
                struct.items = new ArrayList<Item>(_list20.size);
                for (int _i21 = 0; _i21 < _list20.size; ++_i21)
                {
                  Item _elem22; // required
                  _elem22 = new Item();
                  _elem22.read(iprot);
                  struct.items.add(_elem22);
                }
                iprot.readListEnd();
              }
              struct.setItemsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NOCACHE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.nocache = iprot.readBool();
              struct.setNocacheIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryStr struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STARTTIME_FIELD_DESC);
      oprot.writeI64(struct.starttime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ENDTIME_FIELD_DESC);
      oprot.writeI64(struct.endtime);
      oprot.writeFieldEnd();
      if (struct.items != null) {
        oprot.writeFieldBegin(ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.items.size()));
          for (Item _iter23 : struct.items)
          {
            _iter23.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NOCACHE_FIELD_DESC);
      oprot.writeBool(struct.nocache);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryStrTupleSchemeFactory implements SchemeFactory {
    public QueryStrTupleScheme getScheme() {
      return new QueryStrTupleScheme();
    }
  }

  private static class QueryStrTupleScheme extends TupleScheme<QueryStr> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryStr struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStarttime()) {
        optionals.set(0);
      }
      if (struct.isSetEndtime()) {
        optionals.set(1);
      }
      if (struct.isSetItems()) {
        optionals.set(2);
      }
      if (struct.isSetNocache()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetStarttime()) {
        oprot.writeI64(struct.starttime);
      }
      if (struct.isSetEndtime()) {
        oprot.writeI64(struct.endtime);
      }
      if (struct.isSetItems()) {
        {
          oprot.writeI32(struct.items.size());
          for (Item _iter24 : struct.items)
          {
            _iter24.write(oprot);
          }
        }
      }
      if (struct.isSetNocache()) {
        oprot.writeBool(struct.nocache);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryStr struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.starttime = iprot.readI64();
        struct.setStarttimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.endtime = iprot.readI64();
        struct.setEndtimeIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list25 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.items = new ArrayList<Item>(_list25.size);
          for (int _i26 = 0; _i26 < _list25.size; ++_i26)
          {
            Item _elem27; // required
            _elem27 = new Item();
            _elem27.read(iprot);
            struct.items.add(_elem27);
          }
        }
        struct.setItemsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.nocache = iprot.readBool();
        struct.setNocacheIsSet(true);
      }
    }
  }

}

