// ----------------------------------------------------------------
// thrift api for tsdb
//
// This is a Thrift interface definition file for the WatchBase service.
// Target language libraries for C++, Java, Ruby, PHP, (and more) are
// generated by running this file through the Thrift compiler with the
// appropriate flags. The Thrift compiler binary and runtime
// libraries for various languages are available
// from the Apache Incubator (http://incubator.apache.org/thrift/)
// ----------------------------------------------------------------

namespace java net.opentsdb.tsd
namespace py tsd

struct Metric {
    1: i64      timestamp
    2: string   metric
    3: map<string, string>  tags
    4: double   value
}
 
service TSDBService {
    /**
     * Put metrics to tsdb.
     *
     * @return success or not
     */
    bool Put(1: list<Metric> metrics)
}

